### ISSUE TITLE
Prepare a "Sheet" for music personal preferences

### ISSUE THREAD

**Issue by epistimi4** [epistimi4/emotion_based_music_recomendation#1]
- Decide which data we have to include to gather information on music preferences based on mood

- Compile a data set which then will be distributed in different people to record their preferences

- Decide about our music sources e.g. Spottily,  YouTube ...

- Is it possible to find an anonymous way to collect the data?

**Comment by natalitsa** [comment]
- Gender, Age, Song-Artist, Mood, Time of the Day, Location, Activity
Regarding the features Mood, Time of the Day, Location, Activity users should use values from the specific list
- https://drive.google.com/open?id=11PqRUMDKp_THHd6oWWHOWjlTpEWvOrrNNEfU9CyxrfA

-  Spotify and YouTube

- N/A
