### ISSUE TITLE
Define dataset structure

### ISSUE THREAD

**Issue by epistimi4** [epistimi4/emotion_based_music_recomendation#6]
Based on the data that we can gather from Youtube, Spottify and personal info, decide which metadata we should use for our dataset

**Comment by matsarou** [comment]
@epistimi4 @athinabikaki @natalitsa 
Regarding the spotify songs, didn't we agree to **export** all the metadata in the dataset? For the correlations maybe we will use less than what spotify gives us. However, shall we display them all?

**Comment by matsarou** [comment]
For the spotify songs I think we want the audio features. {"acousticness",  "danceability" ,  "liveness",  "loudness" ,  "speechiness"}. Maybe the "instrumentalness" too.

**Comment by athinabikaki** [comment]
also energy and valence

**Comment by matsarou** [comment]
final  list of spotify metadata={"acousticness", "danceability" , "loudness" , "speechiness","energy","valence"}
